const usersInfo = [
	{
		id: 'mattakvshi',
		name: 'Maksim Sidorenko',
		country: 'Russia',
		city: 'Krasnodar',
		district: 'Severny',
		profileImg: `${process.env.PUBLIC_URL}/tmpProfileImg/8_IMG_3596.jpg`,
		notificationOptions: [{ id: '1' }, { id: '2' }, { id: '3' }],
		groups: [
			{
				groupID: '23455',
				groupName: 'Family',
				selectedColor: '#FF4C2B',
				notificationOptions: [{ id: '3' }],
				country: 'Russia',
				city: 'Krasnodar',
				district: 'Severny',
			},
			{
				groupID: '56325',
				groupName: 'Colleagues',
				selectedColor: '#FF4C2B',
				notificationOptions: [{ id: '1' }],
				country: 'Russia',
				city: 'Krasnodar',
				district: 'Karasunsky',
			},
		],
		friends: [
			{ id: '2' },
			{ id: '3' },
			{ id: '4' },
			{ id: '5' },
			{ id: '6' },
			{ id: '7' },
			{ id: '8' },
			{ id: '9' },
			{ id: '10' },
			{ id: '11' },
			{ id: '12' },
			{ id: '13' },
			{ id: '14' },
			{ id: '15' },
			{ id: '16' },
			{ id: '17' },
			{ id: '18' },
			{ id: '19' },
			{ id: '20' },
			{ id: '21' },
			{ id: '22' },
			{ id: '23' },
			{ id: '24' },
			{ id: '25' },
			{ id: '26' },
			{ id: '27' },
			{ id: '28' },
		],
		templates: [{ id: '1' }, { id: '3' }],
	},
	{
		id: '2',
		name: 'Anton Ivanov',
		country: 'Russia',
		city: 'Krasnodar',
		district: 'Polini Osipenko',
		notificationOptions: [{ id: '1' }, { id: '2' }, { id: '3' }],
		groups: [
			{
				groupID: '27357',
				groupName: 'Family',
				selectedColor: '#FF4C2B',
			},
			{
				groupID: '28564',
				groupName: 'Neighbors',
				selectedColor: '#344756',
			},
			{
				groupID: '73898',
				groupName: 'Homies',
				selectedColor: '#480059',
			},
		],
		templates: [{ id: '2' }, { id: '4' }, { id: '5' }, { id: '6' }],
	},
	{
		id: '3',
		name: 'Aleksandr Emelyanenko',
		notificationOptions: [{ id: '1' }, { id: '2' }],
		country: 'Russia',
		city: 'Krasnodar',
		district: 'Kamsamolsky',
		groups: [
			{
				groupID: '23455',
				groupName: 'Groupmates',
				selectedColor: '#098092',
			},
			{
				groupID: '56325',
				groupName: 'Classmates',
				selectedColor: '#3093',
			},
		],
	},
	{
		id: '4',
		name: 'Dmitry Vladarchuk',
		country: 'Russia',
		city: 'Krasnodar',
		district: 'East depot',
		notificationOptions: [{ id: '1' }, { id: '3' }],
		groups: [
			{
				groupID: '23455',
				groupName: 'Closers',
				selectedColor: '#436334',
			},
			{
				groupID: '56325',
				groupName: 'Homies',
				selectedColor: '#ff9309',
			},
		],
	},
	{
		id: '5',
		name: 'Yuriy Sankin',
		country: 'Russia',
		city: 'Krasnodar',
		district: 'Panorama',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '6',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '7',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '8',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '9',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '10',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '11',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '12',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '13',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '14',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '15',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '16',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '17',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '18',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '19',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '20',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '21',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '22',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '23',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '24',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '25',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '26',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '27',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
	{
		id: '28',
		name: 'Defaul default',
		country: 'Russia',
		city: 'Default',
		district: 'Default',
		notificationOptions: [{ id: '3' }],
	},
];

export { usersInfo };
